version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: agrocure_mongo
    ports:
      - "27017:27017"
    volumes:
      - agrocure_mongo_data:/data/db
    restart: unless-stopped

volumes:
  agrocure_mongo_data:
