import { demoStore } from '../utils/demoStore.js';

export const downloadDocument = async (req, res) => {
  try {
    const { id } = req.params;
    const doc = demoStore.documents.find(d => d.id === id || d.docNumber === id) || demoStore.documents[0];

    const htmlContent = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${doc.title} - AgroCure</title>
      <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; background-color: #FAF9F5; color: #1e293b; }
        .card { background: #fff; padding: 30px; border: 2px solid #166534; border-radius: 12px; max-width: 650px; margin: 0 auto; box-shadow: 0 4px 12px rgba(0,0,0,0.05); }
        .header { display: flex; justify-content: space-between; border-bottom: 2px dashed #e2e8f0; padding-bottom: 20px; margin-bottom: 20px; }
        .brand { font-size: 24px; font-weight: bold; color: #166534; }
        .subtitle { font-size: 12px; color: #64748b; }
        .doc-title { font-size: 18px; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; color: #0f172a; margin-bottom: 15px; }
        .row { display: flex; justify-content: space-between; margin-bottom: 12px; font-size: 14px; }
        .label { color: #64748b; }
        .value { font-weight: 600; }
        .footer { margin-top: 30px; font-size: 11px; color: #94a3b8; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 15px; }
        .seal { display: inline-block; padding: 6px 16px; background-color: #dcfce7; color: #15803d; border-radius: 20px; font-weight: bold; font-size: 12px; margin-top: 15px; }
      </style>
    </head>
    <body>
      <div class="card">
        <div class="header">
          <div>
            <div class="brand">AGROCURE</div>
            <div class="subtitle">Government Procurement Experience Layer | SIH 2026</div>
          </div>
          <div style="text-align: right;">
            <div style="font-weight: bold; color: #166534;">${doc.docNumber}</div>
            <div class="subtitle">${doc.date}</div>
          </div>
        </div>

        <div class="doc-title">${doc.title}</div>

        <div class="row">
          <span class="label">Farmer Name</span>
          <span class="value">${doc.farmerName}</span>
        </div>
        <div class="row">
          <span class="label">Crop & Quantity</span>
          <span class="value">${doc.crop}</span>
        </div>
        <div class="row">
          <span class="label">Amount / Status</span>
          <span class="value" style="color: #166534;">${doc.amount}</span>
        </div>
        <div class="row">
          <span class="label">Procurement Centre</span>
          <span class="value">Mandi Bhawan, Sector 12</span>
        </div>
        <div class="row">
          <span class="label">Verification Authority</span>
          <span class="value">AgroCure Procurement Portal</span>
        </div>

        <div style="text-align: center;">
          <div class="seal">OFFICIALLY VERIFIED & DIGITALLY SIGNED</div>
        </div>

        <div class="footer">
          This is an official digital record generated by AgroCure. Know your crop, know your procurement, know your payment.
        </div>
      </div>
      <script>window.print();</script>
    </body>
    </html>
    `;

    res.setHeader('Content-Type', 'text/html');
    return res.status(200).send(htmlContent);
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};
